#!/bin/bash
set -e

if ! type -p fzf >/dev/null; then
  echo "'fzf' not found on the system" >&2
  exit 1
fi

dest_branch="$(git branch -a | fzf)"
dest_branch="${dest_branch//\ /}"

if [ -z "${dest_branch}" ]; then
  exit 2
fi

if [[ "${dest_branch}" =~ \* ]]; then
  echo "Already in dest branch"
  exit 1
fi

echo "Checkout to ${dest_branch}"

if [[ "${dest_branch}" =~ remotes ]]; then
  git checkout -b "${dest_branch//remotes\/origin\//}" "${dest_branch//remotes\//}"
else
  git checkout "${dest_branch}"
fi
